// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YgoCardEngine.EntityFrameworkCore.EntityFrameworkCore;

namespace YgoCardEngine.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(YgoCardEngineDbContext))]
    partial class YgoCardEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("YgoCardEngine.Domain.Card.CardDatas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attribute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Def")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("datas");
                });

            modelBuilder.Entity("YgoCardEngine.Domain.Card.CardTexts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str14")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str15")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str16")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Str9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("texts");
                });
#pragma warning restore 612, 618
        }
    }
}
