<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20200930155837_CreateUserCardGroupTable.cs" />
    <Compile Remove="Migrations\20200930155837_CreateUserCardGroupTable.Designer.cs" />
    <Compile Remove="Migrations\20200930165704_CreateUserCardGroupTable_01.cs" />
    <Compile Remove="Migrations\20200930165704_CreateUserCardGroupTable_01.Designer.cs" />
    <Compile Remove="Migrations\20200930170437_UpdateSomeProps.cs" />
    <Compile Remove="Migrations\20200930170437_UpdateSomeProps.Designer.cs" />
    <Compile Remove="Migrations\20200930170620_UpdateSomeProps.cs" />
    <Compile Remove="Migrations\20200930170620_UpdateSomeProps.Designer.cs" />
    <Compile Remove="Migrations\20200930170726_UpdateSomeProps.cs" />
    <Compile Remove="Migrations\20200930170726_UpdateSomeProps.Designer.cs" />
    <Compile Remove="Migrations\20201007152559_AlterUserTable.cs" />
    <Compile Remove="Migrations\20201007152559_AlterUserTable.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YgoCardEngine.Domain\YgoCardEngine.Domain.csproj" />
  </ItemGroup>

</Project>
